
version: '3.8'

services:
  # Pack Calculator API
  api:
    build: .
    container_name: pack-calculator-api
    environment:
      PC_SERVER_PORT: 8080
      PC_SERVER_HOST: "0.0.0.0"
      PC_APP_ENVIRONMENT: "production"
      PC_APP_NAME: "pack-calculator"
      PC_APP_VERSION: "1.0.0"
      PC_LOGGING_LEVEL: "info"
      PC_LOGGING_FORMAT: "json"
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`pack-calculator.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    networks:
      - pack-network

  # Traefik - Modern reverse proxy with automatic service discovery
  traefik:
    image: traefik:v3.0
    container_name: pack-calculator-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"      # HTTP
      - "8080:8080"  # Traefik dashboard (dev only)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
    networks:
      - pack-network
networks:
  pack-network:
    driver: bridge

